### ISSUE TITLE
deleting paste, new: .git dir not found

### ISSUE THREAD

**Issue by cweiske** [cweiske/phorkie#25]
after deleting a paste, I'm redirected to /new and get:

> Paste 437 .git dir not found

```
#0 /home/cweiske/Dev/phorkie/src/phorkie/Repository.php(74): phorkie\Repository->loadDirs()
#1 /home/cweiske/Dev/phorkie/src/phorkie/Database/Adapter/Elasticsearch/Search.php(67): phorkie\Repository->loadById(16)
#2 /home/cweiske/Dev/phorkie/www/new.php(31): phorkie\Database_Adapter_Elasticsearch_Search->listAll(0, 5, 'modate', 'desc')
#3 {main}
```

**Comment by cweiske** [comment]
This is a race condition; elasticsearch still has it in its index and "/new" tries to list the recent pastes - including the one that does not exist anymore.
